engines:
  duplications:
    enabled: false
    config:
      languages:
        #mass_threshold: 30
        - javascript
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "src/js/app.js"
    - "src/inverted-index.js"
    - "jasmine/specs/*"
languages:
  JavaScript: true
exclude_paths:
- "src/public/css"
- "src/public/images"
- .gitignore
- .eslintignore
- .travis.yml
- .eslintrc.json
- "jasmine/lib"
- "jasmine/testfiles"
- "gulpfile.js"